name: clawsmail # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '4.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The user-friendly, lightweight and fast email client
description: |
    Claws Mail is an email client (and news reader), based on GTK+, featuring
    Quick response
    Graceful, and sophisticated interface
    Easy configuration, intuitive operation
    Abundant features
    Extensibility
    Robustness and stability 
    The appearance and interface are designed to be familiar to new users coming from other popular email clients, as well as experienced users. Almost all commands are accessible with the keyboard.
    The messages are managed in the standard MH format, which features fast access and data security. You'll be able to import your emails from almost any other email client, and export them just as easily.
    Lots of extra functionality, like an RSS aggregator, calendar, or laptop LED handling, are provided by extra plugins.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  clawsmail:
    command: usr/local/bin/claws-mail
    plugs: [home, x11, desktop, desktop-legacy, network, network-bind, network-control]
    extensions: [ gnome-3-38 ]
parts:
  main:
    source: https://www.claws-mail.org/download.php?file=releases/claws-mail-4.1.1.tar.gz
    # See 'snapcraft plugins'
    plugin: autotools

    stage-packages:
      - desktop-file-utils
      - libasn1-8-heimdal
      - libassuan0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libcompfaceg1
      - libcurl3-gnutls
      - libdatrie1
      - libepoxy0
      - libetpan20
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgpgme11
      - libgraphite2-3
      - libgssapi3-heimdal
      - libgtk-3-0
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libice6
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - liblockfile1
      - libnghttp2-14
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsm6
      - libssh-4
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      
    build-packages:
      - pkg-config
      - libncurses5-dev
      - aspell
      - autotools-dev
      - bison
      - flex
      - gettext
      - libaspell-dev
      - libcompfaceg1-dev
      - libetpan-dev
      - libglib2.0-dev
      - libgpgme11-dev
      - libgtk-3-dev
      - libldap2-dev
      - libltdl3-dev
      - libreadline-dev
      - libssl-dev
      - libbt-dev
      - libtool
      - network-manager-dev
      - quilt
